CREATE DATABASE wildlife_tracker;
\c wildlife_tracker;
CREATE TABLE animals(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    health varchar,
    age varchar
);

CREATE TABLE sightings(
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      location varchar,
      ranger varchar
);

\dt
SELECT * FROM animals;
SELECT * FROM sightings;

CREATE DATABASE wildlife_tracker_test WITH TEMPLATE wildlife_tracker;
\c wildlife_tracker_test;